language: node_js
node_js:
  - "7"
install:
    - npm install -g codecov
    - npm install -g codeclimate-test-reporter
    - "npm install"
script:
    - "npm run test"
addons:
    code_climate:
        repo_token: 5ec4b0e880d65561a20f43673221a18971b20a5bd21899429161868ee7cb7338
after_script:
    - codeclimate-test-reporter < ./coverage/lcov.info
    - codecov
